#!/bin/bash


#is there an argument?
if [[ ! $1 ]]; then
	echo "Missing Argument"
	exit 1
fi

scriptname="$1"
bindir="${HOME}/bin"
filename="${bindir}/$1"

#check file already exists?
if [[ -e $filename ]]; then
	echo "File ${filename} already exists"
	exit 1
fi


#Check os there already a command with the name
if type "$scriptname"; then
	echo "Filename ${scriptname} is a existing command"
	exit 1
fi



#Check bin directory exists
if [[ ! -d $bindir ]]; then
	if mkdir "$bindir"; then
		echo "created ${bindir}"
	else
		echo "Could not create ${bindir}"
		exit 1
	fi
fi


#create a script with a single line
echo '#!/bin/bash' > "$filename"

#add executable permission
chmod u+x "$filename"

#Open with editor
if [[ $EDITOR ]]; then
	$EDITOR "$filename"
else
	echo "Script created, not starting editor becouse \$Editor is not set"
fi
exit 0;


